server:
  port: 8083

spring:
  application:
    name: pharmacy-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:microservice-pharmacies

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka