server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: pharmacy-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:microservice-pharmacies
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'