server:
  port: 8085

spring:
  application:
    name: delivery-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:microservice-delivery
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    function:
      definition: deliveryNotificator
    stream:
      bindings:
        deliveryNotificator-in-0:
          destination: recipes
          group: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka