server:
  port: 0

spring:
  application:
    name: drug-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:microservice-drugs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka