server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: drug-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:microservice-drugs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'