server:
  port: ${SERVER_PORT:8080}

drug:
  service:
    url: ${DRUG_SERVIE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}