server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}