server:
  port: 8085

spring:
  application:
    name: recipe-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:microservice-recipes
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    function:
      definition: recipeSender
    stream:
      bindings:
        deliveryNotificator-out-0:
          destination: recipes
          required-groups: main
      source: deliveryNotificator

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka