version: '2.4'

services:
  service-discovery:
    image: microservice-service-discovery:1.0-SNAPSHOT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    environment:
      - SERVER_PORT=8080
    networks:
      - microservices_network

  service-drugs:
    image: microservice-drugs:1.0-SNAPSHOT
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - EUREKA_URL=http://service-discovery:8080/eureka
    networks:
      - microservices_network

networks:
  microservices_network:
    name: microservices_network