version: '2.4'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservices_network

networks:
  microservices_network:
    name: microservices_network