server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'